### ISSUE TITLE
Datasets for BitcoinPredictionRNN.ipynb not found

### ISSUE THREAD

**Issue by Naman1997** [manthanthakker/BitcoinPrediction#1]
The bitbucket does not exist.
`wget 'https://s3.amazonaws.com/sagemakermathan/bitstamp.csv'                                                                         Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.                 ERROR: could not open HSTS store at '/home/ironheart/.wget-hsts'. HSTS will be disabled.              --2019-12-04 22:09:46--  https://s3.amazonaws.com/sagemakermathan/bitstamp.csv                        Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.204.245                                       Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.204.245|:443... connected.                   HTTP request sent, awaiting response... 404 Not Found                                                 2019-12-04 22:09:59 ERROR 404: Not Found.     `

Can you point to an alternate source please?

**Comment by manthanthakker** [comment]
Please use this for realtime data: https://financialmodelingprep.com/api/

**Comment by manthanthakker** [comment]
Added a scrapper for scrapping crypto in real-time: https://github.com/manthanthakker/BitcoinPrediction/blob/master/CryptoScraper.ipynb
