### ISSUE TITLE
How to predict NEW data?

### ISSUE THREAD

**Issue by dmjnlolic** [manthanthakker/BitcoinPrediction#2]
I am wondering how can I predict unknown / future prices for following hours/days, since the input for `model.predict(X)` is actually previous price 'X'?

**Comment by manthanthakker** [comment]
Good question, you can fix the granularity of the data from the source. If you train the network on hourly data, the next X would be hourly, if you train the network on daily data, the next X would daily. The network/hyperparameters remain the same irrespective of the time horizon. Also, please note we subtract the consecutive prices, that is we try to detect if there are any patterns in these movements. Those patterns could be milliseconds/hourly/daily/yearly.
